# Generated by scripts/gen-homebrew-formula.sh in watany-dev/zghalint.
# Edits made here are overwritten by the next release.
class Zghalint < Formula
  desc "Fast, comprehensive GitHub Actions workflow linter"
  homepage "https://github.com/watany-dev/zghalint"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/watany-dev/zghalint/releases/download/v0.0.3/zghalint-macos-aarch64.tar.gz"
      sha256 "dba55d374c30157b53a4ccf0889232afe4b03eb223c662460c4502e859d7c348"
    end
    on_intel do
      url "https://github.com/watany-dev/zghalint/releases/download/v0.0.3/zghalint-macos-x86_64.tar.gz"
      sha256 "22d126d03c7a02453d76d3947d86f0530638d7519e015643fce213d2324c0b3d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/watany-dev/zghalint/releases/download/v0.0.3/zghalint-linux-aarch64.tar.gz"
      sha256 "87d0af31d50210ac2a5450d062bcedd54bbec9d46f4d099a348423821403a1b7"
    end
    on_intel do
      url "https://github.com/watany-dev/zghalint/releases/download/v0.0.3/zghalint-linux-x86_64.tar.gz"
      sha256 "68b4642f0f538bf4e1993c18b6e2752d50f387dacca6a3d71d43ff6c4826b754"
    end
  end

  def install
    # Every archive unpacks into a single zghalint-<os>-<arch>/ directory, which
    # Homebrew strips when staging, leaving the binary at the root. The glob is
    # the fallback for a staging that keeps the directory.
    binary = Dir["zghalint-*/zghalint"].first || "zghalint"
    bin.install binary => "zghalint"
  end

  test do
    assert_match "zghalint v#{version}", shell_output("#{bin}/zghalint --version")

    (testpath/"workflow.yml").write <<~YAML
      name: ci
      on:
        push:
          branches: [main]
      permissions:
        contents: read
      jobs:
        build:
          runs-on: ubuntu-latest
          timeout-minutes: 30
          steps:
            - name: Greet
              run: echo hello
    YAML
    system bin/"zghalint", "--offline", "--", testpath/"workflow.yml"
  end
end
